### ISSUE TITLE
node-pre-gyp console.log debug in 1.4.0 release

### ISSUE THREAD

**Issue by mhio** [julianhille/MuhammaraJS#38]
I'm seeing this on stdout when using 1.4.0 via hummus-recipe:
```
this changes julianhille/MuhammaraJS/releases/download/{version}
{node_abi}-{platform}-{arch}-{libc}.tar.gz
{module_name}-v{version}-{node_abi}-{platform}-{arch}.tar.gz
```
Looks like debug that's been added to `node_modules/muhammara/node_modules/node-pre-gyp/lib/util/versioning.js`.

I can't see in the CI config where the node-pre-gyp is being pulled in from, or where changes are being made.

**Comment by julianhille** [comment]
Acknowledged. Something seems to have happened when publishing.
the Muhammara tgz at npmjs and yarnpkg includes a node_modules dir.

Not sure if that should be like that.

**Comment by mhio** [comment]
node-pre-gyp is in [`bundledDependencies`](https://github.com/julianhille/MuhammaraJS/blob/3cfc0c7df5b9c83045113232d3f21c2496842c40/package.json#L40)... I guess there is/was customisation for it to be distributed with hummus? Sorry not too familiar with building native deps.

Thanks for the quick fix

**Comment by mhio** [comment]
and thanks for taking on the maintenance too =D

**Comment by julianhille** [comment]
yeah correct about the bundled dependency. I did not remember that and was a bit confused / surprised that there was a packaged `node_module` directory.

Still waiting for the builds before pushing to npm, but travis-ci is oddly failing when uploading the release to github. Not sure what this is about. I could push anyway to npm, but this would lead to way longer build times and would required installed build tools on other systems. This is why i always wait for all builds to pass / upload (round about 4 hours per build YIKES)

**Comment by julianhille** [comment]
Upload / release will take at least another 4-6 hours. I managed to hit a race condition at github.
The CI somehow created a release twice for a tag.
The website here only showed one release with one asset, but the CI failed with "duplicate entry" or "sequence did not match" (in app veyor). 
After deleting the release and trying to start all over there was suddenly another release for tag 1.4.1 without doing anything.
This release had 61 assets appending. 
I just restarted ci builds for tag 1.4.1 and hope for the best.

**Comment by julianhille** [comment]
BTW feel free to give me a hint whenever a new Electron or node version is out. Don't have my eyes constantly on it. 😂

**Comment by mhio** [comment]
Node publishes releases in a [json file](https://nodejs.org/dist/index.json). I guess you could have a [schedule](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#schedule) for polling that. Most projects keep [github releases](https://docs.github.com/en/rest/reference/repos#releases) up to date too. 

Here's an example of a [`schedule` action checking for changes from SO](https://stackoverflow.com/a/58468828). 

```
name: Get latest release version
on:
  schedule:
    - cron:  '0 10 * * *'
jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_SCOPED_TOKEN }}
      - name: Fetch release version
        run: |
          curl -sL https://api.github.com/repos/swagger-api/swagger-ui/releases/latest | \
          jq -r ".tag_name" > release-versions/swagger-ui-latest.txt
      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$([ -z "`git status --porcelain`" ] && echo "false" || echo "true")
      - name: Commit latest release version
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.name 'Your Name'
          git config --global user.email 'your-email@users.noreply.github.com'
          git commit -am "New release version"
          git push
```
